pretrained: true
checkpoint_dir_path: "osms/tts_modules/encoder/models/checkpoints"
verbose: true

model_hidden_size: 256
model_embedding_size: 256
model_num_layers: 3

learning_rate_init: 1e-4
speakers_per_batch: 64
utterances_per_speaker: 10

MEL_N_CHANNELS: 40