AudioConfigPath: "osms/tts_modules/encoder/main_configs/AudioConfig.yaml"
SpeakerEncoderConfigPath: "osms/tts_modules/encoder/main_configs/dVecModelConfig.yaml"

SynthesizerConfigPath: "osms/tts_modules/synthesizer/main_configs/tacotron_config.yaml"

VocoderConfigPath: "osms/tts_modules/vocoder/main_configs/wavernn_config.yaml"

SPEAKER_ENCODER_CHECKPOINT_PATH: "osms/tts_modules/encoder/models/pretrained.pt"
SYNTHESIZER_CHECKPOINT_PATH: "osms/tts_modules/synthesizer/models/pretrained.pt"
VOCODER_CHECKPOINT_PATH: "osms/tts_modules/vocoder/models/pretrained.pt"

SPEAKER_SPEECH_PATH: "../audio_samples/google_test.wav"
INPUT_TEXTS_PATH: "../texts/test1.txt"
OUTPUT_AUDIO_DIR: "../result_speech"


