MEL_N_CHANNELS: 25
MEL_WINDOW_STEP: 10
MEL_WINDOW_LENGTH: 40
SAMPLING_RATE: 16000
PARTIAL_UTTERANCE_N_FRAMES: 160
inference_n_frames: 80
VAD_WINDOW_LENGTH: 30
VAD_MOVING_AVERAGE_WIDTH: 8
VAD_MAX_SILENCE_LENGTH: 6
AUDIO_NORM_TARGET_dBFS: -30